### ISSUE TITLE
lua-resty-template can not be  render  page content

### ISSUE THREAD

**Issue by sosojustdo** [bungle/lua-resty-template#12]
hi:

    lua-resty-template hello world demo, can not be  render  page content, just print template name why?

**Comment by sosojustdo** [comment]
use lua_resty_template for hello world demo, can not be print normal html content, Yet every time print template name why?

nginx.conf server block:
set $template_location "/usr/local/templates";  
set $template_root "/usr/local/templates";

location /lua_template_4 {  
                default_type 'text/html';  
                lua_code_cache on;  
                content_by_lua_file /usr/local/openresty/lua/test_template_4.lua;  
}

test_template_4.lua code for:

local template = require("resty.template")
template.render("view.html", { message = "Hello, World!" })

**Comment by sosojustdo** [comment]
nginx  error.log  no error log output

**Comment by bungle** [comment]
don't set template_location it is for retrieving template with sub request aka location.capture. It overrides template_root.

**Comment by bungle** [comment]
if template file is not found the template is considered to be a string.

**Comment by bungle** [comment]
Also check that you are using either latest template.lua in this github repository or the latest release 1.5.

**Comment by bungle** [comment]
Your problem may be related to this:
https://github.com/bungle/lua-resty-template/pull/11

It was merged yesterday and the bug is in 1.6-dev, and not in 1.5 (or the latest sources).

**Comment by sosojustdo** [comment]
replace template.lua file, that ok!
thank you @bungle
