### ISSUE TITLE
how try catch template  runtime exception

### ISSUE THREAD

**Issue by sosojustdo** [bungle/lua-resty-template#15]
lua-resty-template using, if you program have runtime exception  I want try catch exception, how to do somthing? for instance catch exception redirect to error page。

**Comment by bungle** [comment]
Use Lua pcall or xpcall. I have been thinking about adding safe-mode with better error messages to template, but it needs some thinking still.

**Comment by sosojustdo** [comment]
Thank you very much @bungle
