### ISSUE TITLE
index.html default

### ISSUE THREAD

**Issue by geemang2000** [bungle/lua-resty-template#16]
I'm using the template.render(ngx.var.uri ..) with a number of nested directories that have index.html in them. 

Users will call app URLs such as:  http://hostname/app, http://hostname/app/subdir

Is there a way to default the render to look for an index.html?
I've tried the nginx directive index index.html; but it doesn't work either.

**Comment by bungle** [comment]
I think you could use this:
https://github.com/bungle/lua-resty-template#using-template_location

You could also put try_files ...; in there.

**Comment by geemang2000** [comment]
I didn't have time to figure out an NGINX solution. But here is what I used instead. 

```
local uri = ngx.var.uri
if string.sub(uri, -1) == '/' then
        uri = uri .. 'index.html'
else
        uri =  .. uri
end 
template.render (uri, { .. })
```
