### ISSUE TITLE
Render a part of page

### ISSUE THREAD

**Issue by ovoshlook** [bungle/lua-resty-template#17]
Hi. I have some example - I have a page. It uses dynamic structure
for example it managing some system and i can create users. So at create button i need open new some modal window/hided form/etc and write user settings. Pressing save will send ajax POST request to my server. I adding user to database and need to show new user on a page. I dont want to rewrite all page. Just a div with users table.

I generating this div but how can i put only this part of page and update i  using template?
thank you.

**Comment by bungle** [comment]
Tou could use Pjax/Turbolinks etc. Or plain jQuery/JS to replace part of you dom with pretendered html that you are receiving from the server. Your ajax call could also return say JSON and then you need to render the content in JS using some JS templating library / framework. You may also check say Pjax header and decide upon it do you want to render only the fragment or decorate the fragment with layout as well. The possibilities are almost endless. There is a lot good in prerendering on server (things that are more convenient to do in server) but sometimes rendering on client is how you would like to things to work. You may also mix and match these easily.

**Comment by bungle** [comment]
@ovoshlook, please reopen, if you have any further questions
