### ISSUE TITLE
How to  modify rendered string?

### ISSUE THREAD

**Issue by pronan** [bungle/lua-resty-template#20]
say,`local res=template.render("index.html",{})`
For some reasons, before sending text to browsers, I want to do some modifications, but nginx is already rendered.
How can I just get a string without sending it to nginx?

**Comment by bungle** [comment]
You can use:

```lua
local res = template.compile "index.html" {}
```

**Comment by lloydzhou** [comment]
@pronan 
also can do some logic in body_filter_by_lua.

**Comment by pronan** [comment]
Thanks dude. Should I close this question or just leave it?

**Comment by bungle** [comment]
Yes, I can confirm that this is answered, so let's close this.
