### ISSUE TITLE
add a pure lua configure method

### ISSUE THREAD

**Issue by lancelijade** [bungle/lua-resty-template#23]
Hi Aapo,

I'm trying use OpenResty's resty command line tools to test your module, and found I cannot setup a template_location or template_root in the nginx's config file ( or maybe I missed something ). 

But, anyway, I think set a pure lua method to setup templete_root is reasonable, and may make the template more easy to use.

Here is my hack, quite ugly but useful for me:

``` lua
    local root = vars and (var.template_root or var.document_root) or prefix
-- hack: injected lua operated template.tpl_root as template root
    if template.tpl_root then root = template.tpl_root end
-- hack end
    if sub(root, -1) == "/" then root = sub(root, 1, -2) end
```

and in my code:

``` lua
local template = require "resty.template"
template.tpl_root = "/some/path/to/template"
template.render("view.html", "hello world")
```

How do you think this?

Lance

**Comment by lancelijade** [comment]
The example code attached to show usage is wrong, but I think you can understand it.  :P

**Comment by lancelijade** [comment]
Ok, after I read template.load() https://github.com/bungle/lua-resty-template#templateload again, I can understand you design. But I still think injecting a configurable variable into loadngx() is useful, because it quite easier compared to reimplement template.load() and maybe readfile().

**Comment by bungle** [comment]
@lancelijade thanks, I'm currently on vacation, but I will look this when I come back (about two weeks).

**Comment by bungle** [comment]
@lancelijade,

Sorry that you have been waiting this for so long. At first it seems to be a good way to do it like you did, but I worry a bit if you have say several web applications, and they both set:

```lua
-- web app 1
template.root = '/web/one'
-- web app 2
template.root = '/web/two'
```

In some weird edge case this could lead to web app 2 using template root of web app 1 or vise versa (e.g. you yield the worker on web app 1, and then web app 2 sets the root, and then you load a template on web app 1).

**Comment by bungle** [comment]
In general I think that these load functions are somewhat wrongly designed. They do too many things. But it is hard to change that without making breaking changes.

**Comment by bungle** [comment]
I think we just need an instance, e.g. make `template.new` to allow you pass the parameters, so that you don't mix them with globals.

**Comment by bungle** [comment]
`2.0` now has:
```
template.root=<path>
template.location=<location>
```

So I am closing this. The `template.new` to create a new instance is also implemented.
