### ISSUE TITLE
just print view.html string ,why?

### ISSUE THREAD

**Issue by z-n** [bungle/lua-resty-template#24]

**Comment by z-n** [comment]
sorry , It's my fault.。。。

**Comment by bungle** [comment]
Care to elaborate more, or should we just close this? I guess you already found the answer. Do we need to document it or something?

**Comment by W1zzardTPU** [comment]
OP's issue was probably that $template_root wasn't set properly, so the filename which was not found got treated as string. I think this should be mentioned a second time in the docs at https://github.com/bungle/lua-resty-template#templaterenderview-context-key-plain

**Comment by bungle** [comment]
Makes sense, :-).

**Comment by bungle** [comment]
Relates a bit to this #23.
