### ISSUE TITLE
Template is not rendered using example from README

### ISSUE THREAD

**Issue by mjb2kmn** [bungle/lua-resty-template#26]
I installed nginx, lua and luarocks and used luarocks to install lua-resty-template.
Using the simple example shown in the README, my page only shows the text "view.html" instead of rendering the contents of the view.html file.
I built a clean environment with current source releases, static linked, on alpine linux.
I get no errors with nginx on debug logging.
Am I missing something, or is the README?

**Comment by bungle** [comment]
@mjb2kmn,

Where did you put your `view.html`? And can you show other configuration? If it is printing `view.html` it is thinking that this template is actually a string, and not a reference to a template file. You can control where the templates are looked with this: https://github.com/bungle/lua-resty-template#nginx--openresty-configuration.

 (I am preparing a patch where absolute paths are always checked as absolute paths, but I have not checked it in yet — this patch is unrelated to this issue).

**Comment by mjb2kmn** [comment]
I missed setting the root directive in my nginx.conf.
The project where I originally encountered the problem has the same cause, thanks for the pointer.
