### ISSUE TITLE
is there a function some func like php's echo in {% %}?

### ISSUE THREAD

**Issue by cuiweixie** [bungle/lua-resty-template#27]
like this:
{*message*}
{%
    print("ssss")
 %}
output:
sssshello world
expecting:
hello wordssss
the sss show not be at the begin?

**Comment by cuiweixie** [comment]
<a href ="{%
   
    local function echo(s)
        ___[#___+1] =s
    end
    echo("http://www.baidu.com")
 %}">baidu</a>

I look into the code. and find this solution, is it ok?

**Comment by bungle** [comment]
Why not:

```lua
{{message)}
{{"ssss"}}
```

**Comment by cuiweixie** [comment]
sometimes the "ssss" maybe generated by some lua code.

**Comment by bungle** [comment]
Then just put that code in there?

```
{{ run_my_code("yeah!") }}
```

**Comment by bungle** [comment]
Another example:

{{ (function() return "sss" end)() }}

**Comment by cuiweixie** [comment]
I think a phper will feel more comfortable if we has a echo function. 
I am trying to move some php codes to openresty.

**Comment by cuiweixie** [comment]
a echo func could make you template more readable

**Comment by bungle** [comment]
Well, I can think about it, but if you are putting code (like a lot of it) in template, you are possibly doing it wrong (aka spaghetti).

**Comment by cuiweixie** [comment]
i will add it in resty.template.

**Comment by bungle** [comment]
Yes, PRs welcome. Not sure though if I will include it, but you can send it. Or just fork it.

**Comment by cuiweixie** [comment]
OK

**Comment by cuiweixie** [comment]
https://github.com/bungle/lua-resty-template/pull/28
here comes the PR.

**Comment by bungle** [comment]
@cuiweixie, thanbk for the PR. Let's see if other vote this as well.
