### ISSUE TITLE
Not worked

### ISSUE THREAD

**Issue by Roland4444** [bungle/lua-resty-template#30]
local template = require "resty.template"
				template.render("view.html")	

There code in Openresty render only view.html on page

**Comment by bungle** [comment]
yes, it cannot find the file. where have you placed it?

**Comment by Roland4444** [comment]
i placed it to  root ptoject folder. Why hes not returned error in this way?

**Comment by bungle** [comment]
because it is not an error. the argument can be string or a reference to file. if it is not a file, then it is treated as a content.

**Comment by bungle** [comment]
See: https://github.com/bungle/lua-resty-template#nginx--openresty-configuration

**Comment by bungle** [comment]
I am closing this as no further info has been provided.
