### ISSUE TITLE
Revise the rule{{}}

### ISSUE THREAD

**Issue by Steven201314** [bungle/lua-resty-template#31]
When use lua-resty-template with vue.js or AngularJS frame ,{{}} will happen conflict. 
For using uniform rules ,change this ({{}}) to {+  +} or {$$} ?

**Comment by bungle** [comment]
I guess you are not particularly happy with this?
https://github.com/bungle/lua-resty-template#embedding-angular-or-other-tags--templating-inside-the-templates

I think configurable tags have good and bad sides. Not sure if want that OR maybe I am still thinking about it.

**Comment by bungle** [comment]
I have considered this a bit, but I don't find it that important to be able to change tags (e.g. through configuration - it would be very simple to implement though). I think that has bad sides that are greater. You can always fork the project and use different tags.
