### ISSUE TITLE
Can `layout = 'foo.html'` be replaced by `local layout = 'foo.html'`?

### ISSUE THREAD

**Issue by xiangnanscu** [bungle/lua-resty-template#40]
Hello, bungle, I notice the examples in README.md which show defining `layout` in the file:
```
{% layout="section.html" %}
<h1>{{message}}</h1>
```
can be added a `local`, the output is the same
```
{% local layout="section.html" %}
<h1>{{message}}</h1>
```
I just wondering:
Is `{% layout="section.html" %}` same to `{% local layout="section.html" %}` ?

**Comment by bungle** [comment]
the layout variable is already defined for you, so it does not make sense to redefine it, just use it.
