### ISSUE TITLE
child template is rendered even if it is not reachable in the logic of layout 

### ISSUE THREAD

**Issue by xiangnanscu** [bungle/lua-resty-template#42]
Hello bungle. I define `err` in `layout.html` to display exception info.But I find that template engine will render `child.html` first even if it should not be rendered in `layout.html`.
I think engine should render layout first then child

lua
```
template.new('child.html', 'layout.html'):process{err='some exception'}
```
layout.html
```
{% if err then %}
  <div class="alert alert-danger">{{err}}</div>
{% else %}
  {*view*}
{% end %}
```
child.html
```
<p>{{some_method_cannot_be_called_when_err_happen()}}</p>
```

**Comment by bungle** [comment]
If you want to render layout first, then just render layout? And then inside layout render the view with include:
https://github.com/bungle/lua-resty-template#template-syntax

**Comment by bungle** [comment]
e.g.

```
{% if err then %}
  <div class="alert alert-danger">{{err}}</div>
{% else %}
  {(child.html)}
{% end %}
```

**Comment by xiangnanscu** [comment]
@bungle Thanks. it works. Actually I am writing a file path based renderer, so now the code like:
## lua
```
template.new('layout.html'):process{child_html_path=ngx.var.document_uri, err=err}
```
## html
```
{% if err then %}
  <div class="alert alert-danger">{{err}}</div>
{% else %}
  {[child_html_path]}
{% end %}
```
but it seems not so elegant. Also, in this form:
```
{% if err then %}
  <div class="alert alert-danger">{{err}}</div>
{% else %}
  {*view*}
{% end %}
```
if `err` does exists,  the engine should not render `{*view*}`  because it won't get saw in the html output. There seems no meaning to render `{*view*}`. Maybe the `process` api should check the second arg first, if it exists, then render layout first. 
What's you opinion?

**Comment by bungle** [comment]
Perhaps with layouts we could do lazy evaluation of a `{*view*}` aka make it a function?

**Comment by bungle** [comment]
Could you try to change:
https://github.com/bungle/lua-resty-template/blob/master/lib/resty/template.lua#L294
```
context.view = template.process(view, context)
```
to
```
context.view = function() template.process(view, context) end
```

And same here:
https://github.com/bungle/lua-resty-template/blob/master/lib/resty/template.lua#L302, and
https://github.com/bungle/lua-resty-template/blob/master/lib/resty/template.lua#L311, and
https://github.com/bungle/lua-resty-template/blob/master/lib/resty/template.lua#L317

**Comment by xiangnanscu** [comment]
@bungle it worked ! excellent ! so what to do next ? make a patch?

**Comment by xiangnanscu** [comment]
I create a pull request
