### ISSUE TITLE
How do I avoid any changes to the message?

### ISSUE THREAD

**Issue by falves1** [bungle/lua-resty-template#48]
My message is a complete HTML table,

`<table border=1 class="dataframe"><tr><th>Description</th><th>Day</th><th>Address</th><th>Units</th><th>Daily</th><th>Rate</th><th>Total</th><th>Billed</th><th>DBilled</th><th>TotalBilled</th><th>Credited</th><th>TotalCredited</th><th>Balance</th><th>Count</th><th>ASR</th><th>ACD</th></tr><tr><td>Billed</td><td>2021-03-09</td><td>8.19.245.4</td><td>409.50</td><td>804.00</td><td>0.00439</td><td>807.20</td><td>$1.80</td><td>$3.53</td><td>$3.54</td><td></td><td>$2.00</td><td>$-1.54</td><td>2536</td><td>38.96</td><td>24.87</td></tr></table>`
I need to pass it in to the template as is, no changes, instead I get
`&lt;table border=1 class=&quot;dataframe&quot;&gt;&lt;tr&gt;&lt;th&gt;Description&lt;&#47;th&gt;&lt;th&gt;Day&lt;&#47;th&gt;&lt;th&gt;Address&lt;&#47;th&gt;&lt;th&gt;Units&lt;&#47;th&gt;&lt;th&gt;Daily&lt;&#47;th&gt;&lt;th&gt;Rate&lt;&#47;th&gt;&lt;th&gt;Total&lt;&#47;th&gt;&lt;th&gt;Billed&lt;&#47;th&gt;&lt;th&gt;DBilled&lt;&#47;th&gt;&lt;th&gt;TotalBilled&lt;&#47;th&gt;&lt;th&gt;Credited&lt;&#47;th&gt;&lt;th&gt;TotalCredited&lt;&#47;th&gt;&lt;th&gt;Balance&lt;&#47;th&gt;&lt;th&gt;Count&lt;&#47;th&gt;&lt;th&gt;ASR&lt;&#47;th&gt;&lt;th&gt;ACD&lt;&#47;th&gt;&lt;&#47;tr&gt;&lt;tr&gt;&lt;td&gt;Billed&lt;&#47;td&gt;&lt;td&gt;2021-03-09&lt;&#47;td&gt;&lt;td&gt;8.19.245.4&lt;&#47;td&gt;&lt;td&gt;409.50&lt;&#47;td&gt;&lt;td&gt;804.00&lt;&#47;td&gt;&lt;td&gt;0.00439&lt;&#47;td&gt;&lt;td&gt;807.20&lt;&#47;td&gt;&lt;td&gt;$1.80&lt;&#47;td&gt;&lt;td&gt;$3.53&lt;&#47;td&gt;&lt;td&gt;$3.54&lt;&#47;td&gt;&lt;td&gt;&lt;&#47;td&gt;&lt;td&gt;$2.00&lt;&#47;td&gt;&lt;td&gt;$-1.54&lt;&#47;td&gt;&lt;td&gt;2536&lt;&#47;td&gt;&lt;td&gt;38.96&lt;&#47;td&gt;&lt;td&gt;24.87&lt;&#47;td&gt;&lt;&#47;tr&gt;&lt;&#47;table&gt;`

I tried to use {-raw}  but It never gets fixed, or I don't know to use it. How do I integrate a string into the template, verbatim?
Is there any other way to do this?

**Comment by falves1** [comment]
My eyes must be playing tricks with me, 
{expression} =={expression} 
Maybe the words need to be enclosed in backticks?

**Comment by kshitijmjoshi** [comment]
I'm sorry. The comment got messed up due to markdown. 

`{{expression}}, writes result of expression - html escaped
{*expression*}, writes result of expression`

So you need to use `{*expression*}` in your HTML

**Comment by bungle** [comment]
Thank you @kshitijmjoshi, feel like it is solved now. @falves1 please reopen if you have any further questions. Thank you. Closing it for now.
