### ISSUE TITLE
overwriting print() does not work in new()

### ISSUE THREAD

**Issue by alisabri** [bungle/lua-resty-template#8]
Hi Aapo,
Thanks for your efforts. 

when template.print() overwritten, template.new(..):render(...) does not tail call :
```javascript
template.print = function(s) return s end

local view = template.new("view.html", "layout.html")
view.title     = "Testing lua-resty-template blocks"
view.message   = "Hello, World!"
view.keywords  = { "test", "lua", "template", "blocks" }
local a=view:render()
```
so "a" should be a string with rendered content. But it does not. Have a look at the code(template.lua), should not it be like :
```javascript
145   return render(layout, context)
```
or am I missing something ?

Regards

**Comment by bungle** [comment]
Hi, I will look at this. Meanwhile, you can just use `tostring` för tables created with `new`, so the last line in your example:

```lua
local a = tostring(view)
```

**Comment by bungle** [comment]
I have fixed this now. I will release v. 1.5 in a following days. But in a meanwhile you can get the latest version from this repository directly. Thanks for letting me know about this.

**Comment by bungle** [comment]
A new version 1.5 is released which contains this fix.
